Repository uibcdf/OpenPocket, pull requests merged in 2022-07, with the labels that each got.

#3 devtools directory added
  devtools/README.md
  devtools/broadcast_requirements.py
  devtools/conda-build/README.md
  devtools/conda-build/build.sh
  devtools/conda-build/meta.yaml
  devtools/conda-envs/README.md
  devtools/conda-envs/build_env.yaml
  devtools/conda-envs/create_conda_env.py
  devtools/conda-envs/development_env.yaml
  devtools/conda-envs/docs_env.yaml
  devtools/conda-envs/importable_env.yaml
  devtools/conda-envs/production_env.yaml
  devtools/conda-envs/setup_env.yaml
  devtools/conda-envs/test_env.yaml
  devtools/conda-envs/update_conda_env.py
  devtools/requirements.yaml
Labels: enhancement

#5 The first structure
  .codecov.yml
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/CI.yaml
  .github/workflows/build_and_upload_conda_packages.yaml
  .github/workflows/sphinx_docs_to_gh_pages.yaml
  .gitignore
  .lgtm.yml
  CODE_OF_CONDUCT.md
  LICENSE
  MANIFEST.in
  openpocket/__init__.py
  openpocket/_version.py
  openpocket/alpha_spheres/__init__.py
  openpocket/alpha_spheres/alpha_spheres.py
  openpocket/tests/test_import.py
  setup.cfg
  setup.py
  versioneer.py
Labels: enhancement

#7 my first pr
  openpocket/alpha_spheres/alpha_spheres.py
Labels: good first issue

#8 The first attempt to make the alpha_spheres class
  openpocket/alpha_spheres/alpha_spheres.py
Labels: enhancement, question
