Repository uibcdf/OpenPocket, pull requests merged in 2022-08, with the labels that each got.

#9 Alpha spheres class improvement
  docs/contents/alpha_spheres.ipynb
  openpocket/alpha_spheres/alpha_spheres.py
  openpocket/alpha_spheres/alpha_spheres_jc.py
Labels: enhancement

#11 A new method to visualize the alpha-spheres was added
  devtools/conda-build/meta.yaml
  devtools/conda-envs/development_env.yaml
  devtools/conda-envs/docs_env.yaml
  devtools/conda-envs/production_env.yaml
  devtools/conda-envs/test_env.yaml
  devtools/requirements.yaml
  docs/contents/alpha_spheres.ipynb
  openpocket/alpha_spheres/alpha_spheres.py
Labels: enhancement

#14 propousal_remove methods
  docs/contents/alpha_spheres.ipynb
  openpocket/alpha_spheres/alpha_spheres.py
  openpocket/alpha_spheres/alpha_spheres_jc.py
Labels: bug, enhancement, help wanted

#16 Propousal for testing the recent removing methods
  openpocket/tests/test_alphaspheres.py
Labels: enhancement, help wanted, question, tests
